version: "3"
services:
  app:
    image: api-vendas:latest
    environment:
      - SECRET=ApiVendasTest
    ports:
      - '3000:3000'
    depends_on:
      - db
    command: sh -c "npm run typeorm:run migration:run && npm run dev"

  db:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: apivendas
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

